# Generated by Django 4.1.2 on 2022-10-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0002_alter_articles_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('author', 'content_type', 'object_id')},
        ),
    ]
