# Generated by Django 4.1.2 on 2022-10-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
