# Generated by Django 4.1.2 on 2022-10-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0003_rename_genre_books_genres_alter_books_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Readers',
            new_name='Reader',
        ),
    ]
