# Generated by Django 4.1.2 on 2022-10-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookCatalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
